version: 2

models:
  - name: fct__organizations_balance
    description: Daily organization balances with balance change tracking and significant change detection
    columns:
      - name: organization_id
        description: Unique identifier for the organization
        tests:
          - not_null
      - name: balance_date
        description: Date of the balance record
        tests:
          - not_null
      - name: daily_balance_change_usd
        description: Daily balance change in USD
        tests:
          - not_null
      - name: daily_invoices_count
        description: Number of invoices on this day
        tests:
          - not_null
      - name: daily_invoices_paid_count
        description: Number of invoices paid on this day
        tests: 
          - not_null
      - name: daily_invoices_refunded_count
        description: Number of invoices refunded on this day
        tests:
          - not_null
      - name: balance_usd
        description: Cumulative balance up to and including this day
      - name: previous_balance_usd
        description: Balance from the previous day
      - name: days_since_last_balance_change
        description: Number of days since the last balance change
      - name: balance_change_percentage
        description: Percentage change in balance compared to previous day
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - organization_id
            - balance_date
